#------------------------------------------------------
#                  TIMBER CONFIGURATIONS
#------------------------------------------------------
#
# This file contains all timber configuration
#
#

#------------------- Views folder --------------------
views_location: /views

#---------------------- Links ------------------------
links:
  archives:
    news: post
  pages:
    page_exemple: 2